export const OPEN_CONCEPT_GRID = 'OPEN_CONCEPT_GRID';
export const CLOSE_CONCEPT_GRID = 'CLOSE_CONCEPT_GRID';

export const GET_FASHION_ARTICLES_INIT = 'GET_FASHION_ARTICLES_INIT';
export const GET_FASHION_ARTICLES_SUCCESS = 'GET_FASHION_ARTICLES_SUCCESS';
export const GET_FASHION_ARTICLES_FAIL = 'GET_FASHION_ARTICLES_FAIL';


